認証・認可機能の実装
aws-samples/simple-lex-kendra-jp pull request #49
Opened 2023-05-12 06:47 UTC by wadabee

*Issue #, if available:*
close #37 #38

*Description of changes:*
* KendraAuthStack の新規追加
  * Cognito User Pool を利用した認証機能の実装
  * Kendra Index の S3 ドキュメントについて、認証情報によるアクセスコントロールを実装

2023-05-12 08:09 UTC, tbrand commented
## その他のコメント

Warning ですが、デプロイ時にこちらが出ないように対応お願いいたします！

`[Warning at /SimpleKendraAuthStack/KendraUserPool/Resource] AwsSolutions-COG2: The Cognito user pool does not require MFA.`

## UI について

画面右上にハンバーガーメニューがあると思うのですが、最初発見できなかったくらい分かりにくいです！あと挙動もハンバーガーメニューの挙動じゃないため違和感がありました。

![スクリーンショット 2023-05-12 16 58 28](https://github.com/aws-samples/simple-lex-kendra-jp/assets/3483230/be088710-10ee-4dd3-a849-ef7d612281b1)

just idea ですが、よくあるような感じでユーザー名でドロップダウンメニューにしてはいかがでしょうか？(パワポで適当に作ったものなので色などは無視でお願いします)

![スクリーンショット 2023-05-12 17 03 04](https://github.com/aws-samples/simple-lex-kendra-jp/assets/3483230/ea832b64-2f44-453e-ae55-0f843bdab18a)

あるいは、情報量も機能も少ないのでグループ名もどっかに表示しつつサインアウトボタンを右上に出しても良いかもしれません。(わざわざメニューとして出さなくても良いかも？という意味。)

2023-05-12 08:12 UTC, tbrand requested changes

2023-05-12 08:13 UTC, tbrand commented
追加ですいません、あとこのコンテキストであれば API Gateway の認証は必要だと思うので、Cognito Authorizer を設定すべきと思います！

2023-05-12 09:02 UTC, wadabee commented on web-kendra-auth/package.json
> +    "buffer": "^6.0.3",
Amplify UIのDependencyの中に互換性問題を抱えているもの？が含まれているみたいで、以下のエラーが発生してしまいます。
そちらのエラー対応になります。
```
Module not found: Error: Can't resolve 'buffer' in '/Users/wadaysk/Workspace/forked/simple-lex-kendra-jp/node_modules/@aws-amplify/datastore/lib-esm'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
```

2023-05-12 09:04 UTC, wadabee commented on web-kendra-auth/webpack.config.js
> +module.exports = {
上述のAmplify UIのビルドエラー対応で追加しました。

2023-05-12 09:12 UTC, wadabee commented on cdk/lib/simple-kendra-auth-stack.ts
> +
認証で利用しているS3ドキュメント以外は削除しました。

2023-05-12 09:12 UTC, wadabee commented on cdk/lib/simple-kendra-auth-stack.ts
> +
上述の通り、S3ドキュメント以外は削除しました。

2023-05-15 00:35 UTC, wadabee commented on web-kendra-auth/src/lib/useLoginUser.ts
> +      session?.getAccessToken().payload['cognito:groups'] ?? '[未所属]',
確かに、userGroupを取得する役割のものが"[未所属]"を返すのはおかしいですね。
nullを返して、コンポーネント側で"[未所属]"を設定する様にしました！

2023-05-15 00:39 UTC, wadabee commented on web-kendra-auth/src/lib/useLoginUser.ts
> +    token: session?.getAccessToken().getJwtToken() ?? '',
nullの方が扱いやすいのnullに修正しました！

2023-05-15 01:26 UTC, wadabee commented on cdk/lambda/query.ts
> +      // [Auth 拡張実装] リクエストにアクセストークンが設定されていれば、Tokenとして設定する
分割実装しました！

2023-05-15 05:30 UTC, wadabee commented on web-kendra-auth/src/lib/fetcher.ts
> +export const sendQuery = async (api: string, query: string, token?: string) => {
Kendra用に設定していたカスタムHeaderを廃止して、CognitoAuthorizer用のトークンのみにしました。
トークンは原則的に設定されるので、型定義上もトークンを必須にしました。

2023-05-15 05:31 UTC, wadabee commented on web-kendra-auth/src/lib/fetcher.ts
> +      'x-kendra-access-token': token ?? '',
上述の通り、Cognito Authorizer用のトークンと統合しました。

2023-05-15 07:23 UTC, wadabee commented on cdk/lib/simple-kendra-auth-stack.ts
> +      },
デモ用に最大限まで緩い設定にしました！
念の為、nagのsuppression設定箇所に`FIXME`でコメントを入れています。

2023-05-15 07:23 UTC, wadabee commented on cdk/lib/simple-kendra-auth-stack.ts
> +    const identityPool = new idPool.IdentityPool(
Authenticated Userのみダウンロードできる様に修正しました。

2023-05-16 03:05 UTC, tbrand reviewed
細かなところをコメントさせていただきました！

2023-05-16 03:05 UTC, tbrand commented on web-kendra-auth/src/components/TypeDocument.tsx
> +              [COGNITO_ID]: token ?? '',
空の token を渡して期待する機能はないと思うので、downloadFile 関数の最初に token の存在確認をして、ない場合は早期 return で良いと思いますー！

2023-05-16 03:05 UTC, tbrand commented on docs/06_TECH_KNOWLEDGE.md
> +  * 参考：[Access control for Amazon S3 data sources](https://docs.aws.amazon.com/kendra/latest/dg/s3-acl.html)
現状で「フォルダ単位での指定も可能ですので、大量のドキュメントに対してアクセスコントロールを行う場合は、こちらの方法が管理しやすいと思います。  」という pros を書いていただいていますが、もう少し知見を書いていただけると今後のためになると思います！例えば metadata ならきめ細やかな制御、属性も付与したい、ドキュメントを自動生成している場合はついでに作れる、とか。何かあればで良いです。

2023-05-16 04:21 UTC, wadabee commented on cdk/lambda/query.ts
> +    Object.assign({
すみません。修正漏れでしたので、削除しました。

2023-05-16 04:54 UTC, wadabee commented on docs/05_DEPLOY_KENDRA_AUTH.md
> +本プロジェクトは認証を行う必要がありますので、ユーザ登録を行います。
ドキュメントにフロントエンドから登録する手順を追記しました！

2023-05-16 04:55 UTC, wadabee commented on docs/06_TECH_KNOWLEDGE.md
> +  * 参考：[Access control for Amazon S3 data sources](https://docs.aws.amazon.com/kendra/latest/dg/s3-acl.html)
こちらは、ブログでより詳細に書こうと思います！
ブログが公開されたタイミングで、リンクを追記します！

2023-05-16 05:02 UTC, tbrand approved these changes
ありがとうございました！LGTM

2023-05-16 05:02 UTC, merged